### ISSUE TITLE
Create a variable for the core part of the Spotify API

### ISSUE THREAD

**Issue by mml1** [marksimmonds/jammming#3]
All throughout the Spotify.js file, you make calls to the Spotify API. In order to save you from writing the API path over and over again, save the core part ,`https://api.spotify.com/v1`, in a variable. Having a variable for the API core will also help when testing between development and production. Usually, you have a development API hitting a development database before using your code in production. The core between the development and production APIs path will differ, but the rest of the routes will be the same. Thus, if you have a variable for the core route, you can change between production and development mode quite easily.

https://github.com/marksimmonds/jammming/blob/master/src/util/Spotify.js

**Comment by marksimmonds** [comment]
Thanks for the advice. I have now added a variable 'apiURL' to spotify.js, and modifed the code to reflect the above variable where required.
