### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mml1** [marksimmonds/jammming#4]
[Exceeds Expectations] Awesome work! Great job deploying to surge and meeting the spec. I was able to add/remove tracks, save playlist, change playlist title, search by artist/album/title, and see the matching tracks! In terms of improvement, I would suggest saving the core part of the API route in a variable. Overall, brilliant! 👍

**Comment by marksimmonds** [comment]
Thanks! I've made the suggested changes, and started work on the feature request. A lot of my gained knowledge on this course has included the periphery things like using github and surge, so glad to get those working as well. Cheers, Mark.
