### ISSUE TITLE
Caveats

### ISSUE THREAD

**Issue by ghost** [marksimmonds/jammming#8]
> Since the ‘SEARCH’ button still exists as an option for the user, it is not expected to cause any unexpected behaviours from the users’ perspective. Additionally, as this is standard behaviour on many websites, users will likely be expecting the process to occur by default.

Fair. Any caveats as far as choosing this particular approach to the problem? Did you consider or research any other possible solutions?

> The only alternative possibility is via the existing ‘SEARCH’ bar, which will still remain in place, as well as this new feature.

Alternative possibility of?

**Comment by marksimmonds** [comment]
I didn't research other options, although when programming the feature up I did have a solution that updated the search for each keystroke, which I actually thought was quite a good feature and did consider implementing that instead. I should definitely have put that in the document as an alternative option though.

'Alternative possibility of' refers to starting the search function to retrieve a subset of songs/artists/albums including the search term.
