### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [marksimmonds/jammming#9]
Satisfactory

Your suggested implementation will work and your design is straightforward enough for another programmer to follow, but it is not an optimal solution. It's pretty easy to reach for this solution, especially when you've just spent so much time learning about React and all the wonderful things it can do for your web development projects. 

The simplest way to implement this feature does not require any React skill at all, not even any JavaScript! Throwing in a second event listener/event handler pair just adds unnecessary lines to your codebase as you add more and more forms to your application. It's not ideal for so much of your code to be dedicated almost exclusively to duplicating form submission logic. At the very least, this is a tradeoff that you should consider in your request.

A quick Google would demonstrate how you might implement this with just HTML. All you really need is to change your `div` element to a `form`, use a single `onSubmit` event listener, and change the `a` element to an `input` element of `type="submit"`. Try it out!

**Comment by marksimmonds** [comment]
Thanks Steve, I can get that working in a HTML page.  It does means I'd have to change the css files to make it look the same as there is.
update: OK, I finally made it work within the render function of the Searchbar.js file. I also made the necessary changes to the Searchbar.css file to make appearances look same as previously.
